version: '3.7'

services:
  postgres:
    image: kartoza/postgis:11.5-2.5
    container_name: postgres-task-manager
    restart: always
    environment:
      - POSTGRES_USER=transaction_db
      - POSTGRES_PASSWORD=pass111
      - POSTGRES_DB=TransactDb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  task_manager:
    build:
      context: ./
      dockerfile: Dockerfile
    image: task_manager
    container_name: task_manager
    command: /usr/local/bin/gunicorn task_manager.wsgi -w 4 -b 0.0.0.0:8000 -t 0 --reload
    env_file:
      - .env
    ports:
      - "8080:8000"
    volumes:
      - ./app:/app
    depends_on:
      - postgres

volumes:
  postgres_data:
